# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('host', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 't_cluster',
            },
        ),
    ]
