# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
                ('domain', models.CharField(max_length=45, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_account.Role')),
            ],
            options={
                'db_table': 't_account',
            },
        ),
    ]
